# -*- coding: utf-8 -*-
"""space_race_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dOeg-UwvJKwtljohzXMcEQM-Nh05Msu8
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install iso3166

#%pip install --upgrade plotly

import numpy as np
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

# These might be helpful:
from iso3166 import countries_by_name
from datetime import datetime, timedelta, date

#converts string dates to datetime
def parse_date(date_str):
    try:
        return pd.to_datetime(date_str, format='%a %b %d, %Y %H:%M UTC')
    except:
        try:
            return pd.to_datetime(date_str, format='%a %b %d, %Y')
        except:
            try:
                return pd.to_datetime(date_str)
            except:
                return pd.NaT

pd.options.display.float_format = '{:,.2f}'.format

cold_war_countries = ['USSR', 'USA']

df_launch = pd.read_csv('/content/mission_launches.csv')
df_launch.drop_duplicates(inplace=True)
df = df_launch.drop(['Unnamed: 0.1', 'Unnamed: 0'], axis=1).copy()
df['Date'] = df['Date'].apply(parse_date)
df['year'] = df['Date'].dt.year
df['month'] = df['Date'].dt.strftime("%B")
df['country'] = df['Location'].str.split(',').str[-1].str.strip()


max_year = df['year'].max()

#multiple different dfs, 1) 2000-2020, 2)Cold war <1991 3) all years
df_cold = df.copy()
df_cold['country'] = df_cold['country'].replace({'Kazakhstan': 'USSR', 'Russia' : 'USSR'})
df_cold = df_cold[df_cold['country'].isin(cold_war_countries)]
df_cold = df_cold[df_cold['year'] < 1991]
df_all = df.copy()
df = df[(df['year'] > 2000) & (df['year'] < max_year)]

#looks at total number of launches overall since 2000 per organisation
df_organisations = df.copy()
df_organisations = df_organisations[['Organisation']]
df_organisations = df_organisations.value_counts()
df_organisations = df_organisations.reset_index(name='count')


fig, ax = plt.subplots(figsize=(15, 8))

sns.barplot(
    df_organisations,
    x='Organisation',
    y='count',
    hue='count',
    palette='mako',
    legend=False
    )

ax.set_xlabel("Organisation", fontsize=14, labelpad=15)
ax.set_ylabel("Total Number of Launches", fontsize=14, labelpad=15)
ax.set_title("Space Launch Frequency by Organisation (2000-2020)", pad=15, fontweight='bold', fontsize=15)
plt.xticks(rotation=60)

plt.tight_layout()
plt.show()

#compares rocket active or retired status  overall since 2000 per organisation
df_active = df.copy()
df_active = df_active[['Organisation', 'Rocket_Status']]
df_active = df_active.value_counts()
df_active = df_active.reset_index(name='count')

fig, ax = plt.subplots(figsize=(25, 10))

sns.barplot(
    df_active,
    x="Organisation",
    y="count",
    hue="Rocket_Status",
    palette='mako',
    edgecolor='white',
    )


ax.set_xlabel("Organisation", fontsize=14, labelpad=15)
ax.set_ylabel("Rocket Count", fontsize=14, labelpad=15)
ax.set_title("Active vs. Retired Rocket Launches by Organisation (2000-2020)", pad=15, fontweight='bold', fontsize=15)
plt.xticks(rotation=60)

plt.tight_layout()
plt.show()

#compares overall active verse inactive rockets
df_active_value = df_active['Rocket_Status'].value_counts()
df_active_value = df_active_value.rename(index={'StatusActive': 'Active Rockets','StatusRetired': 'Unactive Rockets'})

labels = [f"{active} ({count} Rockets)" for active, count in zip(df_active_value.index, df_active_value.values)]

fig, ax = plt.subplots(figsize=(8, 8))

colors = sns.color_palette("mako", n_colors=4)

wedges, texts, autotexts = ax.pie(
    df_active_value.values,
    autopct='%1.0f%%',
    labeldistance=1.1,
    pctdistance=0.7,
    startangle=180,
    wedgeprops={'edgecolor': 'white'},
    textprops={'color': 'black'},
    colors=colors
)


#color inside pie chart
for autotext in autotexts:
    autotext.set_color("white"),
    autotext.set_fontsize(15)

ax.set_ylabel('')

plt.title(
    "Total Active vs. Unactive Rockets (2000-2020)",
    fontsize=15,
    fontweight="bold",
    color="black",
    loc="center"
    )
ax.legend(wedges, labels, title="Rockets", loc="center left", bbox_to_anchor=(1, 0.5))
plt.show()

#compares mission status by organisation
df_success = df.copy()
df_success = df_success[['Organisation', 'Mission_Status']]
df_success = df_success.value_counts()
df_success = df_success.reset_index(name='count')


fig, ax = plt.subplots(figsize=(18, 10))

sns.barplot(
    df_success,
    x="Organisation",
    y="count",
    hue="Mission_Status",
    palette='mako',
    width=.9,
    edgecolor='white',
    )
plt.yscale('log')
plt.ylabel("Total Launches (log scale)", fontsize=14, labelpad=15)
ax.set_xlabel("Organisation", fontsize=14, labelpad=15)
ax.set_title("Mission Status by Organisation (2000-2020)", pad=15, fontweight='bold', fontsize=15)
plt.xticks(rotation=60)

plt.show()

#overall mission statuses for all launches 2000-2020
df_success_value = df_success['Mission_Status'].value_counts()

labels = [f"{status} ({count} Rockets)" for status, count in zip(df_success_value.index, df_success_value.values)]

fig, ax = plt.subplots(figsize=(8, 8))

wedges, texts, autotexts = ax.pie(
    df_success_value.values,
    autopct='%1.0f%%',
    labeldistance=1.1,
    pctdistance=0.7,
    startangle=180,
    wedgeprops={'edgecolor': 'white'},
    textprops={'color': 'black'},
    colors=colors
)


#color inside pie chart
for autotext in autotexts:
    autotext.set_color("white"),
    autotext.set_fontsize(15)

ax.set_ylabel('')

plt.title(
    "Mission Status for all Launches",
    fontsize=15,
    fontweight="bold",
    color="black",
    loc="center"
    )
ax.legend(wedges, labels, title="Rockets", loc="center left", bbox_to_anchor=(1, 0.5))
plt.show()

df_expense = df.copy()
df_expense['Price'] = df_expense['Price'].str.replace(',', '')
df_expense['Price'] = df_expense['Price'].astype(float)
df_expense = df_expense.dropna(subset=['Price'])


fig, ax = plt.subplots(figsize=(15, 8))

sns.histplot(
    df_expense['Price'],
    bins=30,
    color=sns.color_palette("mako", 1)[0],
    edgecolor='white',
    stat='percent'
)
ax.set_xlabel("Launch Cost (USD millions)", fontsize=14, labelpad=15)
ax.set_ylabel("Rocket Launch Frequency (Percent)", fontsize=14, labelpad=15)
plt.title("Rocket Launch Costs (2000-2020)", pad=15, fontweight='bold', fontsize=15)


plt.tight_layout()
plt.show()

#choropleth graph of total rocket launches by country 2000-2020
df_country = df.copy()
df_country = df_country[['Location', 'Mission_Status']].copy()
df_country['Location'] = (df_country['Location'].str.replace(r"[\[\]']", "", regex=True).str.split(','))
df_country['Country'] = df_country['Location'].str[-1].str.strip().str.upper()
df_country['Country'] = df_country['Country'].replace({'RUSSIA' : 'RUSSIAN FEDERATION',
                                                       'USA': 'UNITED STATES OF AMERICA',
                                                       'NEW MEXICO' : 'UNITED STATES OF AMERICA',
                                                       'IRAN' : 'IRAN, ISLAMIC REPUBLIC OF',
                                                       'YELLOW SEA' : 'CHINA',
                                                       'NORTH KOREA' : "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
                                                       'PACIFIC MISSILE RANGE FACILITY' : 'UNITED STATES OF AMERICA',
                                                       'PACIFIC OCEAN' : 'UNITED STATES OF AMERICA',
                                                       'SOUTH KOREA' : 'KOREA, REPUBLIC OF',
                                                       'BARENTS SEA' : 'UNITED STATES OF AMERICA',
                                                       'GUINEA' : 'GUINEA-BISSAU',

                                                       })

for row in df_country.itertuples():
  df_country['ISO'] = df_country['Country'].apply(lambda x: countries_by_name[x.upper()].alpha3)

country_count = df_country['ISO'].value_counts()

fig = px.choropleth(
    country_count,
    locations= country_count.index,
    color= country_count.values,
    hover_name=country_count.index,
    color_continuous_scale='Viridis',
    labels = {'color': 'Total Rocket Launches '}

)

fig.update_layout(geo_bgcolor='white', title={'text': '<b>Global Rocket Launches by Country (2000-2020)<b>', 'x':0.5, 'xanchor': 'center'}, title_font_size=18, width=1800, height=900)
fig.update_coloraxes(colorbar_title='Rocket Launches', colorbar_tickfont=dict(size=12))


fig.show()

#rocket failure count by country 2000-2020
df_failure = df_country.copy()
df_failure = df_failure[df_failure['Mission_Status'] == 'Failure']
df_failure = df_failure['ISO'].value_counts()

fig = px.choropleth(
    df_failure,
    locations= df_failure.index,
    color= df_failure.values,
    hover_name=df_failure.index,
    color_continuous_scale='Viridis',
    labels = {'color': 'Total Rocket Launch Failures '}

)


fig.update_layout(geo_bgcolor='white', title={'text': '<b>Total Rocket Launch Failures by Country<b>', 'x':0.5, 'xanchor': 'center'}, title_font_size=18, width=1800, height=900)
fig.update_coloraxes(colorbar_title=' Rocket Launches ', colorbar_tickfont=dict(size=12), )


fig.show()

#sunburst chart of country, organisation, and mission status from 2000-2020
sunburst_chart = df.copy()
sunburst_chart['Location'] = (sunburst_chart['Location'].str.replace(r"[\[\]']", "", regex=True).str.split(','))
sunburst_chart['Country'] = sunburst_chart['Location'].str[-1].str.strip()

sunburst_chart_counted = sunburst_chart.groupby(['Country', 'Organisation', 'Mission_Status']).size().reset_index(name='count')

fig = px.sunburst(
    sunburst_chart_counted,
    path=['Country', 'Organisation', 'Mission_Status'],
    values='count',
    color='count',
    color_continuous_scale='RdBu',
    width=3600,
    height=1800,
    )


fig.update_layout(geo_bgcolor='white', title={'text': '<b>Overall Mission Status from each organisation and their country<b>', 'x':0.5, 'xanchor': 'center'}, title_font_size=25)
fig.write_html("sunburst_chart.html")
fig.show()

#looks at top spending by oranisation in 2000-2020
df_org_money = df.copy()
df_org_money = df_org_money[['Organisation', 'Price']]
df_org_money = df_org_money.dropna(subset=['Price'])
df_org_money['Price'] = df_org_money['Price'].str.replace(',', '')
df_org_money['Price'] = df_org_money['Price'].astype(float)
df_org_money = df_org_money.groupby('Organisation')['Price'].sum().reset_index()
df_org_money = df_org_money.sort_values(by='Price', ascending=False)

fig, ax = plt.subplots(figsize=(15, 8))

sns.barplot(
    df_org_money,
    x="Organisation",
    y="Price",
    hue="Price",
    width=.9,
    palette='mako',
    )

ax.set_title('Total Amount of Money Spent by Organisation', pad=15, fontweight='bold', fontsize=15)
ax.set_xlabel("Organisation", fontsize=14, labelpad=15)
ax.set_ylabel("Amount Spent (Million)", fontsize=14, labelpad=15)

plt.xticks(rotation=45)

plt.show()

df_launch_per_year = df.copy()
df_launch_per_year = df_launch_per_year.groupby('year').size().reset_index(name='count')

fig, ax = plt.subplots(figsize=(15, 8))

sns.barplot(
    df_launch_per_year,
    x="year",
    y="count",
    hue="count",
    width=.9,
    palette='mako'
    )

ax.set_title('Launches Per Year', pad=15, fontweight='bold', fontsize=15)
ax.set_xlabel("Year", fontsize=14, labelpad=15)
ax.set_ylabel("Number of Launches", fontsize=14, labelpad=15)

plt.xticks(rotation=45)

plt.show()

df_launch_per_month = df.copy()
df_launch_per_month = df_launch_per_month.groupby('month').size().reset_index(name='count')
df_launch_per_month['avg_month'] = df_launch_per_month['count']/19
df_launch_per_month['month'] = df_launch_per_month['month'].sort_values()

fig, ax = plt.subplots(figsize=(15, 8))

sns.barplot(
    df_launch_per_month,
    x="month",
    y="avg_month",
    hue="avg_month",
    width=.9,
    order=['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    palette='mako',
    )

ax.set_title('Average Launches Per Month (2000-2020)', pad=15, fontweight='bold', fontsize=15)
ax.set_xlabel("Month", fontsize=14, labelpad=15)
ax.set_ylabel("Average Number of Launches", fontsize=14, labelpad=15)

plt.xticks(rotation=45)

plt.show()

df_cost_time = df[['year', 'Price']].copy()
df_cost_time = df_cost_time.dropna(subset=['Price'])
df_cost_time['Price'] = df_cost_time['Price'].str.replace(',', '')
df_cost_time['Price'] = df_cost_time['Price'].astype(float)
df_cost_time = df_cost_time.groupby(['year'], sort=True)['Price'].mean().reset_index()


fig, ax1 = plt.subplots(figsize=(20, 5))

sns.lineplot(
    data=df_cost_time,
    x="year",
    y="Price",
    sort=False
    )

plt.title(
    "Comparison of Launch Prices Overtime (2000-2020)",
    fontsize=15,
    fontweight='bold',
    pad=20
    )

ax1.set_ylabel('Average Cost of Launch (Million)', fontsize=14, labelpad=15)
ax1.set_xlabel('Year', fontsize=14, labelpad=15)

ax1.set_xticks(df_cost_time['year'])
ax1.set_xticklabels(df_cost_time['year'].astype(int), rotation=45)


plt.tight_layout()
plt.show()

#total launches from the top ten organisations
top_ten = df.copy()
top_ten = top_ten.groupby('Organisation').size().reset_index(name='count').sort_values(by='count', ascending=False)
top_ten = top_ten.head(10)

fig, ax = plt.subplots(figsize=(15, 8))

sns.barplot(
    top_ten,
    x="Organisation",
    y="count",
    hue="count",
    width=.9,
    palette='mako'
    )


ax.set_title(' Number of Launches over Time by the Top 10 Organisations', pad=15, fontweight='bold', fontsize=15)
ax.set_xlabel("Year", fontsize=14, labelpad=15)
ax.set_ylabel("Number of Launches", fontsize=14, labelpad=15)

plt.xticks(rotation=45)

plt.show()

#looking at the number of launches from the top ten countries
org_colors = {
    'CASC': 'blue',
    'Arianespace': 'red',
    'Roscosmos': 'pink',
    'ULA': 'green',
    'VKS RF': 'purple',
    'SpaceX': 'orange',
    'ISRO': 'brown',
    'MHI': 'cyan',
    'Northrop': 'grey',
    'Boeing': 'black'
}

fig, ax = plt.subplots(figsize=(20, 6))

for org, color in org_colors.items():
    org_count = (df.loc[df['Organisation'] == org].groupby('year').size().reset_index(name='count'))
    sns.lineplot(
        data=org_count,
        x="year",
        y="count",
        ax=ax,
        label=org,
        color=color
    )

ax.set_title("Number of Launches from the Top Ten Companies (2000-2020)", fontsize=15, fontweight='bold', pad=20)
ax.set_ylabel('Number of Launches',  fontsize=14, labelpad=15)
ax.set_xlabel('Year',  fontsize=14, labelpad=15)

ax.set_xticks(sorted(df['year'].unique()))
ax.set_xticklabels(sorted(df['year'].unique()), rotation=45)


ax.legend(title='Organisation')
plt.tight_layout()
plt.show()

df_cold_counts = df_cold.groupby('country').size().reset_index(name='count')

labels = [f"{country} ({count} Rockets)" for country, count in zip(df_cold_counts['country'], df_cold_counts['count'])]

fig, ax = plt.subplots(figsize=(8, 8))

wedges, texts, autotexts = ax.pie(
    df_cold_counts['count'],
    labels=None,
    autopct='%1.0f%%',
    labeldistance=1.1,
    pctdistance=0.7,
    startangle=180,
    wedgeprops={'edgecolor': 'white'},
    textprops={'color': 'black'},
    colors=colors

)

# Style inside text
for autotext in autotexts:
    autotext.set_color("white")
    autotext.set_fontsize(15)

ax.set_ylabel('')
plt.title(
    "The Cold War: \nRocket Launch Comparison between USA and USSR",
    fontsize=15,
    fontweight="bold",
    color="black",
    loc="center"
)

# Legend on the side
ax.legend(wedges, labels, title="Rocket Count", loc="center left", bbox_to_anchor=(1, 0.5))
plt.tight_layout()
plt.show()

#comparison of usa and ussr rocket launches during the cold war
df_cold_year = df_cold.copy()
df_cold_year = (df_cold_year.groupby(['year', 'country']).size().reset_index(name='count'))

stacked_bar = df_cold_year.pivot(index='year', columns='country', values='count').fillna(0)
stacked_bar.plot(
    kind='bar',
    stacked=True,
    figsize=(14, 8),
    color=[colors[1],colors[3]],
    width=.9,
    edgecolor='white',

    )

plt.ylabel('Number of Launches', fontsize=14, labelpad=15)
plt.xlabel('Year',  fontsize=14, labelpad=15)
plt.title("The Cold War: \nRocket Launches Per Year", fontweight='bold', fontsize=15, pad=15)
plt.legend(title='Country')
plt.tight_layout()
plt.xticks(rotation=45)
plt.show()

df_cold_failures = df_cold.copy()
df_cold_failures = df_cold_failures[df_cold_failures['Mission_Status'].str.contains('Failure', case=False, na=False)]

df_cold_failures = (df_cold_failures.groupby(['year', 'country']).size().reset_index(name='count'))

stacked_bar = df_cold_failures.pivot(index='year', columns='country', values='count').fillna(0)
stacked_bar.sort_index(inplace=True)


stacked_bar.plot(
    kind='bar',
    stacked=True,
    figsize=(14, 8),
    color=[colors[1],colors[3]],
    width=.9,
    edgecolor='white',
    )

plt.ylabel('Number of Failures Per Year', labelpad=15, fontsize=14)
plt.xlabel('Year', labelpad=15, fontsize=14)
plt.title("The Cold War: \nTotal Rocket Launch Failures Per Year", fontweight='bold', fontsize=15, pad=15)
plt.legend(title='Country')
plt.tight_layout()
plt.xticks(rotation=45)
plt.show()

df_percent_failures = df_cold.copy()
df_percent_failures['year'] = df_percent_failures['year'].astype(int)
df_percent_failures = df_percent_failures.groupby(['country', 'year', 'Mission_Status']).size().reset_index(name='count')
df_percent_failures

df_pivot = df_percent_failures.pivot_table(index=['country', 'year'],columns='Mission_Status',values='count',aggfunc='sum',fill_value=0).reset_index()


df_pivot['fail'] = df_pivot.get('Failure', 0) + df_pivot.get('Partial Failure', 0) + df_pivot.get('Prelaunch Failure', 0)
df_pivot['success'] = df_pivot.get('Success', 0)

df_result = df_pivot[['country', 'year', 'fail', 'success']]
df_result['percent_failure'] = (df_result['fail'] / (df_result['fail'] + df_result['success'])) * 100
df_result = df_result.drop(columns=['fail', 'success'])


df_result = df_result.pivot(index='year', columns='country', values='percent_failure')

ax = df_result.plot(
    kind='bar',
    figsize=(14, 8),
    width=0.8,
    color=[colors[1],colors[3]],
    edgecolor='white',
)

plt.ylabel('Percent Failure of Launches (%)', labelpad=15)
plt.xlabel('Year', labelpad=10)
plt.title('The Cold War: \nPercentage of Launches that Ended in Failure', fontweight='bold', fontsize=15, pad=15)
plt.xticks(rotation=45)
plt.legend(title='Country')
plt.tight_layout()
plt.show()

#looking at launch numbers per country (2000-2020)
df_launches = df.copy()
df_launches['year'] = df_launches['year'].astype(int)
df_launches = df_launches.groupby(['country', 'year']).size().reset_index(name='count')

country_colors = {
    'Barents Sea': 'blue',
    'Brazil': 'green',
    'China': 'red',
    'France': 'cyan',
    'India': 'purple',
    'Iran': 'orange',
    'Israel': 'brown',
    'Japan': 'pink',
    'Kazakhstan': 'yellow',
    'New Mexico': 'grey',
    'New Zealand': 'lime',
    'North Korea': 'magenta',
    'Pacific Missile Range Facility': 'teal',
    'Pacific Ocean': 'navy',
    'Russia': 'maroon',
    'South Korea': 'olive',
    'USA': 'black',
    'Yellow Sea': 'gold'
}

fig, ax = plt.subplots(figsize=(20, 5))

for place, color in country_colors.items():
    country_count = df_launches[df_launches['country'] == place]
    if not country_count.empty:  # skip countries with no data
        sns.lineplot(
            data=country_count,
            x="year",
            y="count",
            ax=ax,
            label=place,
            color=color
        )

ax.set_title("Number of Launches Per Country (2000-2020)", fontsize=15, fontweight='bold', pad=20)
ax.set_ylabel('Number of Launches', labelpad=15, fontsize=14)
ax.set_xlabel('Year', labelpad=15, fontsize=14)

years = sorted(df_launches['year'].unique())
ax.set_xticks(years)
ax.set_xticklabels(years, rotation=45)

ax.legend(title='Country', bbox_to_anchor=(1.02, 1), loc='upper left', borderaxespad=0)
plt.tight_layout()
plt.show()

df_top_launches = df_all.copy()
df_top_launches['year'] = df_top_launches['year'].astype(int)
df_top_launches = df_top_launches.groupby(['country', 'year']).size().reset_index(name='count')

idx = df_top_launches.groupby('year')['count'].idxmax()
highest_per_year = df_top_launches.loc[idx]


fig, ax = plt.subplots(figsize=(15, 8))

sns.barplot(
    highest_per_year,
    x="year",
    y="count",
    hue="country",
    palette='mako',
    width=.9
)

plt.ylabel('Launch Count', labelpad=15, fontsize=14)
plt.xlabel('Year', labelpad=10, fontsize=14)
plt.title("Country with Most Launches of Each Year", fontweight='bold', fontsize=15, pad=15)
plt.legend(title='Country')
plt.tight_layout()
plt.xticks(rotation=45)
plt.show()

df_top_org_launches = df_all.copy()
df_top_org_launches['year'] = df_top_launches['year'].astype(int)
df_top_org_launches = df_top_org_launches.groupby(['Organisation', 'year']).size().reset_index(name='count')

idx = df_top_org_launches.groupby('year')['count'].idxmax()
highest_org_per_year = df_top_org_launches.loc[idx]
highest_org_per_year['year'] = highest_org_per_year['year'].astype(int)

fig, ax = plt.subplots(figsize=(15, 8))

sns.barplot(
    highest_org_per_year,
    x="year",
    y="count",
    hue="Organisation",
    palette='mako',
    width=.9
)

plt.ylabel('Launch Count', labelpad=15, fontsize=14)
plt.xlabel('Year', labelpad=15, fontsize=14)
plt.title("Organisation with Most Launches of that Year", fontweight='bold', fontsize=15, pad=15)
plt.legend(title='Country')
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()